import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const montSerratFont = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"]
                                  })

export const metadata: Metadata = {
  title: "MyBank Front-End",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montSerratFont.className} relative antialiased grid grid-rows-[auto_1fr] h-screen`}
      >
      <Header />
      <main className="overflow-auto">
        {children}
      </main>
      </body>
    </html>
  );
}
